### ISSUE TITLE
WP Geo Recent Locations widget

### ISSUE THREAD

**Issue by faxuno** [benhuson/WP-Geo#71]
Hello!

I'm the webmaster of www.lightheplanet.net

Is it possible to have the "WP Geo Recent Locations" widget in a new page of the blog?

I mean, there is a code to catch to insert the same map with customized width and height in a single page?

**Comment by snecz** [comment]
Hello, do you have WP Geo widget working?

**Comment by faxuno** [comment]
Yes, you can see in the website ...

**Comment by benhuson** [comment]
Do you want to display the same map but in a page/post rather than a widget in the sidebar?

You can do this with the [`[wpgeo_mashup]`](https://github.com/benhuson/WP-Geo/blob/master/includes/shortcodes.php#L172) shortcode.

By default this shows all markers but you should be able to limit it to a number of recent ones using the `posts_per_page` attribute.

 `[wpgeo_mashup posts_per_page="10"]`

**Comment by snecz** [comment]
Thanks, working great now :)
