### ISSUE TITLE
Update for Wordpress 5

### ISSUE THREAD

**Issue by Fussverkehr** [benhuson/WP-Geo#96]
Hello,

will you do an update for Wordpress 5. I still like your plugin. 

Kind regards
Dominik

**Comment by quitoxic** [comment]
Hi Ben, 
I assume you have your hands full. 
I also love your plugin as it's simple and easy to use but it's been a long time since the last update and has an issue with WPML and others. 
Would love to see an update, I would not mind at all to pay the plugin, as mentioned I think is the perfect solution for what I need!

**Comment by benhuson** [comment]
Please try version 3.5.1 and let me know if that now works for you?

Thanks

**Comment by quitoxic** [comment]
Yes, it's sorted :)
You are an all-star! The map was not loading on the admin for English other languages. Now everything works correctly. 
Thank you again.

**Comment by benhuson** [comment]
Great :)
